import type { Metadata } from 'next'
import './globals.css'
import { PropsWithChildren } from 'react'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'
import { montserrat } from './ui'

export const metadata: Metadata = {
  title: 'Fennec Tales Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>

      <body className={`${montserrat.className} flex size-full min-h-screen flex-col bg-primary text-base text-primary-label-primary`}>
        <Header />

        <main className="flex-1 p-4 pt-[90px] md:pt-[66px]">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  )
}
