import type { Metadata } from 'next'
import './globals.css'
import { PropsWithChildren } from 'react'
import { Footer } from '@/components/footer'
import { montserrat } from './ui'
import { ProgressBarProvider } from '@/providers/progress-bar.provider'

export const metadata: Metadata = {
  title: 'Fennec Tales Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>

      <body className={`${montserrat.className} flex size-full min-h-screen flex-col bg-primary text-base text-primary-label-primary`}>
        <ProgressBarProvider>
          {children}
          <Footer />
        </ProgressBarProvider>
      </body>
    </html>
  )
}
